# Generated by Django 4.0.2 on 2022-03-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('year', models.CharField(choices=[('21/22', '21/22'), ('22/23', '22/23')], max_length=5)),
                ('term', models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='madrasa.students')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Management',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='homework',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
