# Generated by Django 4.0.2 on 2022-03-05 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0002_fees_remove_feedback_student_id_delete_management_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fees',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(upload_to='static/e-commerce/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madrasa.teachers')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='audio',
            field=models.ManyToManyField(to='madrasa.Audio'),
        ),
    ]
