# Generated by Django 4.0.2 on 2022-03-05 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0003_alter_fees_date_alter_fees_term_audio_homework_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='audio',
        ),
        migrations.AddField(
            model_name='homework',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='madrasa.audio'),
        ),
    ]
