# Generated by Django 4.0.2 on 2022-03-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0004_remove_homework_audio_homework_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('heard', models.CharField(choices=[('fb', 'Facebook'), ('wom', 'Word of Mouth')], max_length=20, verbose_name='Where did you hear about us?')),
                ('referred', models.CharField(max_length=255, verbose_name="If referred, please include the child's name of the referrer.")),
                ('session', models.CharField(choices=[(1, '9:45 - 11:45'), (2, '12:00 - 14:00'), (3, 'No Preference')], max_length=20, verbose_name='Please specify your preferred session. This is not guaranteed')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name / Middle Names')),
                ('last_name', models.CharField(max_length=255, verbose_name='Surname ')),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('previous_madrasa', models.CharField(max_length=255, verbose_name='Previous Madrasa')),
                ('level_of_study', models.CharField(choices=[(1, 'Qaaidah'), (2, 'Juz Amma'), (3, 'Quran'), (4, 'Tahfiz/Hifz'), (5, 'N/A')], max_length=20)),
                ('photography', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('a1', models.BooleanField(default=False)),
                ('a2', models.BooleanField(default=False)),
                ('a3', models.BooleanField(default=False)),
                ('a4', models.BooleanField(default=False)),
                ('a5', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='static/e-commerce/audios/'),
        ),
    ]
