# Generated by Django 4.0.2 on 2022-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0005_registration_alter_audio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.CharField(default='m@hot.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='photography',
            field=models.BooleanField(default=False),
        ),
    ]
