# Generated by Django 4.0.2 on 2022-03-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0006_students_email_students_photography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='students',
            name='level_of_study',
            field=models.CharField(choices=[('1', 'Qaaidah'), ('2', 'Juz Amma'), ('3', 'Quran'), ('4', 'Tahfiz/Hifz'), ('5', 'N/A')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='previous_madrasa',
            field=models.CharField(default='kkjkj', max_length=255, verbose_name='Previous Madrasa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='level_of_study',
            field=models.CharField(choices=[('1', 'Qaaidah'), ('2', 'Juz Amma'), ('3', 'Quran'), ('4', 'Tahfiz/Hifz'), ('5', 'N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='session',
            field=models.CharField(choices=[('1', '9:45 - 11:45'), ('2', '12:00 - 14:00'), ('3', 'No Preference')], max_length=20, verbose_name='Please specify your preferred session. This is not guaranteed'),
        ),
        migrations.AlterField(
            model_name='students',
            name='which_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='madrasa.classes'),
        ),
    ]
