# Generated by Django 4.0.2 on 2022-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0007_alter_registration_options_students_level_of_study_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='level_of_study',
            field=models.CharField(blank=True, choices=[('1', 'Qaaidah'), ('2', 'Juz Amma'), ('3', 'Quran'), ('4', 'Tahfiz/Hifz'), ('5', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='previous_madrasa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Previous Madrasa'),
        ),
    ]
