# Generated by Django 4.0.2 on 2022-03-15 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0008_alter_students_level_of_study_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='updated',
        ),
        migrations.AddField(
            model_name='audio',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classattendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fees',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='which_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='madrasa.classes'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
