# Generated by Django 4.0.2 on 2022-03-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0009_remove_userprofile_user_remove_attendance_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
    ]
