# Generated by Django 4.0.2 on 2022-03-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0011_roommember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created',
        ),
    ]
