# Generated by Django 4.0.2 on 2022-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0012_remove_students_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='photography',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
