# Generated by Django 4.0.2 on 2022-03-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0014_alter_students_photography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='audio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='madrasa.audio'),
        ),
    ]
