# Generated by Django 4.0.2 on 2022-05-25 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madrasa', '0015_alter_homework_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madrasa.classes'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madrasa.students'),
        ),
        migrations.AlterField(
            model_name='fees',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madrasa.students'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='audio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='madrasa.audio'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madrasa.course'),
        ),
        migrations.AlterField(
            model_name='students',
            name='which_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='madrasa.classes'),
        ),
    ]
